spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/fidle?useSSL=false&useUnicode=true&characterEncoding=UTF8&allowPublicKeyRetrieval=true
        driver-class-name: com.mysql.jdbc.Driver
        username: root
        password: 123456
    thymeleaf:
        cache: false
mybatis:
    type-aliases-package: com.example.fidledemo.DO , com.example.fidledemo.BO
    mapper-locations: classpath*:com/example/fidledemo/dao/*.xml

server:
    port: 8080
imageHost:
    url: http://127.0.0.1:8080/image/
    path: C:\Users\WWJ20\Documents\GitHub\TeamProject-Alpha\fidledemo\src\main\resources\image\


